language: node_js

node_js:
  - "7"
cache:
  directories:
    - node_modules
sudo: false
addons:
  code_climate:
    repo_token: d1f59c45c9e2d639ce2ecf0c699d1413ba1aa1167c0e3e6aab3e1df21a5af127

before_install:
  - npm install -g npm

script:
  - npm test

after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
